version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: segwise_app
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=segwise
      - REDIS_CONN_ADDR=redis:6379
      - REDIS_PASSWORD=
    volumes:
      - ./logs:/app/logs

  postgres:
    image: postgres:15
    container_name: segwise_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: segwise
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: segwise_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    
volumes:
  postgres_data:
  redis_data:
 